swagger: '2.0'
info:
  version: '1.0'
  title: "RequestUnicornAPI"
schemes:
  - https
paths:
  "/ride":
    post:
      description: "post api to request unicorn"
      consumes:
        - application/json
      responses:
        200:
          description: "post for unicorn"
          headers:
            Access-Control-Allow-Origin:
              type:"string"
      x-amazon-apigateway-integration:
        uri: ${post_lambda_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
definitions:
  Empty:
    type: "object"
    title: "test Schema"